# Generated by Django 3.1 on 2020-08-19 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='img',
        ),
        migrations.RemoveField(
            model_name='task',
            name='link',
        ),
        migrations.RemoveField(
            model_name='task',
            name='linktext',
        ),
    ]
