# Generated by Django 3.1 on 2020-08-20 06:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_task_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='img',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000, verbose_name='Зображення'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='linktext',
            field=models.CharField(default=django.utils.timezone.now, max_length=40, verbose_name='Текст силки'),
            preserve_default=False,
        ),
    ]
